#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &>/dev/null && pwd )"

command -v uv >/dev/null \
  ||  { echo "ERROR: uv not found in PATH"; exit 1; }

uv sync --project "$SCRIPT_DIR" --quiet --frozen

exec uv run --project "$SCRIPT_DIR" python -m gh_tt "$@"