import asyncio
from contextlib import contextmanager
import json
import os
from pathlib import Path
import tempfile
import uuid
from datetime import UTC, datetime

from gh_tt.classes.gitter import Gitter


class Testbed:

    @staticmethod
    def generate_name(infix: str = "") -> str:
        """Returns a timestamped name for naming autogenerated resources"""
        
        today_iso = datetime.now(UTC).date().isoformat()

        return f"gh-tt-test-{infix}-{today_iso}-{uuid.uuid4().hex[:8]}"
    
    @staticmethod
    def clean_up(repository_html_url: str, project_number: int):
        """Returns state of the testbed to a blank slate
        
        Args:
            repository_html_url (str): url of the repository to clean up, e.g. https://github.com/vemolista/test-repo
            project_number (int): number of the project to clean up
        """

        # TODO: change to run in CI

        asyncio.run(Gitter(
            cmd=f'gh project delete {project_number} --owner @me',
            msg='Delete GH project'
        ).run())

        asyncio.run(Gitter(
            cmd=f'gh repo delete {repository_html_url} --yes',
            msg='Delete repo'
        ).run())
        
    @staticmethod
    def create_github_resources(owner: str) -> tuple[str, int]:
        """Creates a new repository and project for testing
        
        Returns:
            tuple: (link to repository, project number)
        """

        is_local = os.getenv('CI') != 'true'

        if is_local:
            Gitter.validate_gh_scope('project')
            Gitter.validate_gh_scope('repo')

        else:
            raise NotImplementedError("running in the ci is not implemented")
        
        # create repo
        repo_name = f'{owner}/{Testbed.generate_name(infix='repo')}'
        [repo_html_url, _] = asyncio.run(Gitter(
            cmd=f'gh repo create "{repo_name}" --private',
            msg='Create a testing repository'
        ).run())

        # create project
        project_name = Testbed.generate_name(infix='project')
        [project_number, _] = asyncio.run(Gitter(
            cmd=f'gh project create --title "{project_name}" --owner {owner} --format json --jq ".number"',
            msg='Create a testing project'
        ).run())

        # create default labels
        # TODO init based on config
        label_names = ['development', 'ad hoc', 'rework']
        for name in label_names:
            asyncio.run(Gitter(
                cmd=f'gh label create -R "{repo_html_url}" "{name}"',
                msg='Create label'
            ).run())

        [status_field_id, _] = asyncio.run(Gitter(
            cmd=f'gh project field-list {project_number} --owner {owner} --format json --jq \'.fields[] | select(.name == "Status").id\'',
            msg='Get ID of the Status field'
        ).run())

        # update status field to have options Todo, In Progress, Delivery Initiated and Done
        # TODO init based on config
        cmd = f"""
           gh api graphql -f query='
                mutation {{
                    updateProjectV2Field(input: {{
                        fieldId: "{status_field_id}",
                        singleSelectOptions: [{{name: "Todo", description: "Todo", color: BLUE}}, {{name: "In Progress", description: "In Progress", color: BLUE}}, {{name: "Delivery Initiated", description: "Delivery Initiated", color: BLUE}}, {{name: "Done", description: "Done", color: BLUE}}]
                    }}) {{
                        projectV2Field {{
                            ...on ProjectV2SingleSelectField {{
                                id
                            }}
                        }}
                    }}
                }}
            '
        """

        asyncio.run(Gitter(
            cmd=cmd,
            msg='Add "Delivery Initiated" Status option'
        ).run())

        return repo_html_url, int(project_number)

    @staticmethod
    def gitter_run(cmd: str, cwd: str = Path.cwd()):
        return asyncio.run(Gitter(
            cmd=cmd,
            workdir=cwd
        ).run())
    
    @staticmethod
    def gitter_run_all(cmds: list[str], cwd: str):
        results = []

        for cmd in cmds:
            run_result = Testbed.gitter_run(cmd=cmd, cwd=cwd)
            results.append(run_result)

        return results
    
    @staticmethod
    @contextmanager
    def sandbox_repo(project_number: int, project_owner: str):
        with tempfile.TemporaryDirectory() as td:
            repo = Path(td)
            Testbed.gitter_run_all(cmds=[
                'git init',
                'git branch -m main',
                'git config user.email "me@example.com"',
                'git config user.name "Manual E2E"',
                'git config push.autoSetupRemote true'
            ], cwd=repo)
            (repo / "README.md").write_text("# hi!")
            (repo / ".tt-config.json").write_text(json.dumps({
                "project": {
                    "owner": project_owner,
                    "number": project_number
                }
            }, indent=4))
            Testbed.gitter_run_all(cmds=[
                'git add .',
                'git commit -m "init"'
            ], cwd=repo)

            yield repo

    