name: Spelling

on:
    workflow_call:

permissions:
    contents: read

jobs:
    spelling:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - run: npm install -g cspell

            - name: Check spelling
              run: cspell lint --no-progress --config ./cspell.json &>> $GITHUB_STEP_SUMMARY
