name: CI

on:
  workflow_dispatch:
  merge_group:
  pull_request: 
    branches: 
      - main

# No special permissions defined before we need them
permissions:
  contents: read

env:
  PYTHON_VERSIONS: "['3.12', '3.13', '3.14']"

jobs:

  # It is not possible to pass an environment variable down to
  # a reusable workflow as an argument via _with_.
  # See: https://stackoverflow.com/a/73305536
  # The workaround is to put the environment variable as a step output.
  python_versions:
    name: Set Python versions
    runs-on: ubuntu-latest
    outputs:
      python_versions: ${{ steps.step1.outputs.python_versions }}
    steps:
      - id: step1
        run: echo "python_versions=$PYTHON_VERSIONS" >> "$GITHUB_OUTPUT"

  test:
    name: Test
    needs: python_versions
    permissions:
      contents: read
    uses: ./.github/workflows/callable_pytest_matrix.yaml
    with:
      pytest_arguments: --cov=. --cov-config=.coveragerc -m 'unittest or hypothesis'
      python_versions: ${{ needs.python_versions.outputs.python_versions }}

  lint:
    name: Lint
    permissions:
      contents: read
    uses: ./.github/workflows/callable_ruff_lint.yaml

  format:
    name: Format
    permissions:
      contents: read
    uses: ./.github/workflows/callable_ruff_format.yaml

  type_check:
    name: Type check
    permissions:
      contents: read
    uses: ./.github/workflows/callable_ty_type_check.yaml

  spell_check:
    name: Spell check
    permissions:
      contents: read
    uses: ./.github/workflows/callable_cspell_spell_check.yaml

  test_e2e:
    name: Test E2E
    permissions:
      statuses: write
    secrets: inherit
    uses: ./.github/workflows/end_to_end_test.yml

  check:  # This job does nothing and is only used for the branch protection
    name: ✅ All checks passed
    runs-on: ubuntu-latest
    timeout-minutes: 1
    if: always()
    needs:
    - lint
    - format
    - type_check
    - spell_check
    - test_e2e
    - test

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
