# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Property-based testing
# This workflow is triggered on push to branches that begins with a number (issue-branches)

on:
  workflow_call:
    inputs:
      context:
        description: 'Context for the status check'
        required: false
        type: string
        default: 'Property-based testing'

permissions:
  statuses: write

jobs:
  pbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv and gh dependencies
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          uv sync --extra dev

          gh extension install thetechcollective/gh-set-status --pin stable

      - name: Property-based tests
        id: pbt
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run pytest -m pbt --hypothesis-profile=1000

      - name: Report status
        id: property-based-tests
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
        run: |
          if [ ${{ steps.pbt.outcome }} == 'success' ]; then
            gh set-status success "All integration tests passed" "${{ inputs.context }}"
          else
            gh set-status failure "Some integration tests failed" "${{ inputs.context }}"
            exit 1
          fi
