name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
      fetch-depth: 0
        fetch-depth: 0
        ref: main

    - name: Create GitHub Release
      run: |
        set +e
        SEMVER_TAG="${GITHUB_REF#refs/tags/}"

        echo "Creating release for tag '$SEMVER_TAG'"
        git tag
        git branch

        if git branch --contains "$SEMVER_TAG" main | grep -q "main"; then
          gh release create "$SEMVER_TAG" --generate-notes --verify-tag --latest
        else
          echo "Tag $SEMVER_TAG is not on main, skipping release creation."
          exit 1
        fi