# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Wrapup
# This workflow is triggered on push to branches that begins with a number (issue-branches)

on:
  workflow_dispatch:
  push:
    branches: 
      - '[0-9]*'

# No special permissions defined before we need them
permissions:
  contents: read

jobs:
  # This job will install uv, run the unittests and output the arguments we need to set the status
  verification:

    runs-on: ubuntu-latest
    permissions:
      statuses: write


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv
          . .venv/bin/activate
          uv sync --extra dev
          gh extension install thetechcollective/gh-set-status --pin stable

      - name: Run linter
        run: |
          uv run ruff check . --exit-zero --output-format github

      - name: Test with pytest
        id: Unittest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . .venv/bin/activate 
          pwd
          # Dont exit if the next command fails, we want to capture the exit code
          set +e
          pytest --cov=. --cov-config=.coveragerc -m unittest
          result=$?
          set -e


          if [ $result -eq 0 ]; then
            gh set-status success "All tests passed and threshold on line coverage reached"
          else
            gh set-status failure "Some tests failed or threshold on line covearage not reached"
          fi
          exit $result
